name: Run Cypress Tests

on:
  push:
    branches: [ Develop ]
  pull_request:
    branches: [ Develop ]

jobs:
  cypress-run:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 21 # o tu versión

      - name: Install dependencies
        run: npm install

      - name: Run tests
        run: npm run test
